# Generated by Django 3.2.16 on 2024-01-23 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20240121_1935'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('following',), name='unique_following'),
        ),
    ]
